### ISSUE TITLE
not spawning mobs correctly 

### ISSUE THREAD

**Issue by Atlas-Maker** [0x00002a/Soul-Shards-Despawn#1]
it seems to only be able to spawn the mobs at another entities position and can't spawn them on their own

**Comment by 0x00002a** [comment]
Yeah I encountered this on my own server I think, should be fixed now (will release soon once I've tested it a bit more).

I \*think\* this bug is not entirely my fault and actually existed in the 1.15 fabric version but I'm not sure

**Comment by 0x00002a** [comment]
Fixed in 1.x.3
