### ISSUE TITLE
Error message when connecting to a server

### ISSUE THREAD

**Issue by bblewitt** [0x00002a/Soul-Shards-Despawn#2]
- Minecraft Version: 1.19.2
- Forge Version: 43.2.8
- Mod Version: 1.0.4

Issue:
When connecting to a server with 1.0.4 is causes a **"net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null"**
error message to pop up.
When downgrading to 1.0.3 on the client and server it allows me to connect to the server.

From what I can gather to further help you in finding the issue quickly to push out a new version for 1.19.2+ is that it is a custom recipe implementation or something along those lines as different mods got reports of this same issue.

**Comment by 0x00002a** [comment]
Is both the server and client running 1.0.4?

**Comment by bblewitt** [comment]
Yes both the server and the client are running 1.0.4.
I had to downgrade them both to play on it but as of the error yeah.

**Comment by 0x00002a** [comment]
Reproduced it, I'll see about fixing asap

**Comment by 0x00002a** [comment]
fixed in 1.x.5
